package com.opefago.lib.events.notification.types;

public enum NotificationEventType {
    PUSH_NOTIFICATION, SMS_NOTIFICATION, USER_NOTIFICATION, OTP_SMS,OTP_NOTIFICATION,
    WALLET_WITHDRAWAL_SUCCESS_NOTIFICATION, TRANSFER_SUCCESS_NOTIFICATION,
    WALLET_WITHDRAWAL_FAILED_NOTIFICATION, TRANSFER_FAILED_NOTIFICATION,
    CARD_TOPUP_SUCCESS_NOTIFICATION, BILL_PAYMENT_SUCCESS_NOTIFICATION,
    CARD_TOPUP_FAILED_NOTIFICATION, BILL_PAYMENT_FAILED_NOTIFICATION,
    WALLET_TOPUP_SUCCESS_NOTIFICATION,
    NUBAN_CREATED_NOTIFICATION
}
